<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ReplantedOverhaul</RootNamespace>
	    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	    <Nullable>enable</Nullable>
    </PropertyGroup>

	<PropertyGroup>
		<GamePath>C:\Program Files (x86)\Steam\steamapps\common\PVZ Replanted</GamePath>
		<ModsPath>C:\Program Files (x86)\Steam\steamapps\common\PVZ Replanted\Mods</ModsPath>
		<ExePath>C:\Program Files (x86)\Steam\steamapps\common\PVZ Replanted\Replanted.exe</ExePath>
	</PropertyGroup>

	<!-- BloomEngine -->
	<ItemGroup>
		<Reference Include="BloomEngine">
			<HintPath>..\..\BloomEngine\src\bin\Release\net6.0\BloomEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	
	<!-- MelonLoader, Harmony, Il2CppInterop -->
	<ItemGroup>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)\MelonLoader\net6\MelonLoader.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)\MelonLoader\net6\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>$(GamePath)\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>$(GamePath)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<!-- All other assemblies -->
	<ItemGroup>
		<Reference Include="$(GamePath)\MelonLoader\Il2CppAssemblies\*.dll">
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<!-- Copy build output and Run game -->
    <Target Name="DeployAndLaunch" AfterTargets="Build">
        <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(ModsPath)" />
        <Message Text="Deployed $(AssemblyName).dll to $(GameModsDir)" Importance="high" />
        <Exec Command="cmd /c start &quot;&quot; &quot;steam://rungameid/3654560&quot;" />
    </Target>

</Project>
